# Generated by Django 2.2.7 on 2019-11-19 02:15

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField(blank=True)),
                ('class_number', models.IntegerField(blank=True)),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('catalog', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=400)),
                ('section', models.IntegerField(blank=True)),
                ('instructor', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab', models.CharField(default=[], max_length=100)),
                ('q0', multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', '1'), ('item_key2', '2'), ('item_key3', '3'), ('item_key4', '4'), ('item_key5', '5')], default=[], max_length=49)),
                ('q1', multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', '1'), ('item_key2', '2'), ('item_key3', '3'), ('item_key4', '4'), ('item_key5', '5')], default=[], max_length=49)),
                ('q2', multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', '1'), ('item_key2', '2'), ('item_key3', '3'), ('item_key4', '4'), ('item_key5', '5')], default=[], max_length=49)),
                ('q3', multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', '1'), ('item_key2', '2'), ('item_key3', '3'), ('item_key4', '4'), ('item_key5', '5')], default=[], max_length=49)),
                ('q4', multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', '1'), ('item_key2', '2'), ('item_key3', '3'), ('item_key4', '4'), ('item_key5', '5')], default=[], max_length=49)),
                ('q5', multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', '1'), ('item_key2', '2'), ('item_key3', '3'), ('item_key4', '4'), ('item_key5', '5')], default=[], max_length=49)),
                ('q6', multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', '1'), ('item_key2', '2'), ('item_key3', '3'), ('item_key4', '4'), ('item_key5', '5')], default=[], max_length=49)),
                ('q7', multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', '1'), ('item_key2', '2'), ('item_key3', '3'), ('item_key4', '4'), ('item_key5', '5')], default=[], max_length=49)),
                ('q8', multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', '1'), ('item_key2', '2'), ('item_key3', '3'), ('item_key4', '4'), ('item_key5', '5')], default=[], max_length=49)),
                ('q9', multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', '1'), ('item_key2', '2'), ('item_key3', '3'), ('item_key4', '4'), ('item_key5', '5')], default=[], max_length=49)),
                ('q10', multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', '1'), ('item_key2', '2'), ('item_key3', '3'), ('item_key4', '4'), ('item_key5', '5')], default=[], max_length=49)),
                ('q11', multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', '1'), ('item_key2', '2'), ('item_key3', '3'), ('item_key4', '4'), ('item_key5', '5')], default=[], max_length=49)),
                ('q12', multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', 'less than 2'), ('item_key2', '2'), ('item_key3', '2.5'), ('item_key4', '3'), ('item_key5', 'more than 3')], default=[], max_length=49)),
                ('q13', multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', 'less than 2'), ('item_key2', '2'), ('item_key3', '2.5'), ('item_key4', '3'), ('item_key5', 'more than 3')], default=[], max_length=49)),
                ('q14', multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', 'less than 2'), ('item_key2', '2'), ('item_key3', '2.5'), ('item_key4', '3'), ('item_key5', 'more than 3')], default=[], max_length=49)),
                ('f1', models.TextField(blank=True, null=True)),
                ('f2', models.TextField(blank=True, null=True)),
                ('f3', models.TextField(blank=True, null=True)),
                ('f4', models.TextField(blank=True, null=True)),
                ('f5', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=70, null=True)),
                ('student_id', models.IntegerField(default=0)),
                ('lab1', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='lab1', to='ta.Lab')),
                ('lab2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab2', to='ta.Lab')),
            ],
        ),
    ]
