# Generated by Django 2.2.7 on 2019-11-19 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='lab1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab1', to='ta.Lab'),
        ),
        migrations.AlterField(
            model_name='student',
            name='lab2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab2', to='ta.Lab'),
        ),
    ]
