# Generated by Django 2.2.7 on 2019-11-19 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ta', '0003_student_lab3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.AddField(
            model_name='student',
            name='lab4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab4', to='ta.Lab'),
        ),
        migrations.AddField(
            model_name='student',
            name='lab5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab5', to='ta.Lab'),
        ),
        migrations.AddField(
            model_name='survey',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='ta.Student'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='lab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab', to='ta.Lab'),
        ),
    ]
