# Generated by Django 2.2.7 on 2019-11-19 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta', '0004_auto_20191119_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
