# Generated by Django 2.2.7 on 2019-11-19 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta', '0005_lab_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='completed',
        ),
        migrations.AddField(
            model_name='student',
            name='l1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='l2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='l3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='l4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='l5',
            field=models.BooleanField(default=False),
        ),
    ]
