# Generated by Django 2.2.7 on 2019-12-02 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ta', '0010_auto_20191202_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='lab1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab', to='ta.Student'),
        ),
    ]
